/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user, isLoaded, isSignedIn } = useUser();
  // const { data } = api.example.getAll.useQuery();
  const { data } = api.post.getAll.useQuery();

  // console.log(data);

  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {!isSignedIn && (
            <SignInButton mode="modal">
              <button className="rounded-lg bg-blue-700 py-2 px-6 text-white">
                Sign in
              </button>
            </SignInButton>
          )}
          {isSignedIn && (
            <SignOutButton>
              <button className="rounded-lg bg-blue-700 py-2 px-6 text-white">
                Sign out
              </button>
            </SignOutButton>
          )}
        </div>
        {data?.map((post) => {
          return <div key={post.id}>{post.content}</div>;
        })}
      </main>
    </>
  );
};

export default Home;
